---
- name: Login to ACR
  containers.podman.podman_login:
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"
    registry: "{{ acr_server }}"
  become: true

- name: Update repositories apt cache
  apt:
    update_cache: yes
  become: true

- name: Installing podman
  apt:
    name: "podman"
    state: present
  become: true

- name: Pull image from ACR
  containers.podman.podman_image:
    name: "{{ nginx_image }}"
    pull: yes
  become: true

- name: Create a nginx container
  containers.podman.podman_container:
    name: webserver-nginx
    image: "{{ nginx_image }}"
    state: started
    detach: true
    ports:
    - "0.0.0.0:80:80"
  become: true

- name: Generate systemd allows you to control a container
  containers.podman.podman_generate_systemd:
    name: webserver-nginx
    dest: /etc/systemd/system/
    restart_policy: always
  become: true

- name: Ensure the service is enabled and running
  ansible.builtin.systemd:
    name: "container-webserver-nginx"
    enabled: yes
    state: started
    daemon_reload: yes
  become: true
