all:
  children:
    webservers:
      hosts:
        vm1_fr_22.04_80:
          ansible_host: 20.111.44.210
          ansible_user: azureuser
          ansible_ssh_private_key_file: /home/user/.ssh/vm1_fr_22.04_80_id_rsa
    vm:
      hosts:
        20.111.44.210:
          ansible_user: azureuser
          ansible_ssh_private_key_file: /home/user/.ssh/vm1_fr_22.04_80_id_rsa
    acr:
      hosts:
        localhost:
          ansible_connection: local
  vars:
    acr_name: acrdevopscasopractico2
