all:
  children:
    webservers:
      hosts:
        vm1_fr_22.04_80:
          ansible_host: 20.19.184.88
          ansible_user: azureuser
          ansible_ssh_private_key_file: /home/user/.ssh/vm1_fr_22.04_80_id_rsa
    vm:
      hosts:
        20.19.184.88:
          ansible_user: azureuser
          ansible_ssh_private_key_file: /home/user/.ssh/vm1_fr_22.04_80_id_rsa
    acr:
      hosts:
        localhost:
          ansible_connection: local
  vars:
    acr_name: acrdevopscasopractico2
